name: Node.js Package

env:
  TZ: Asia/Shanghai

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 0 * * *"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      run: |
        cd ./logi.im/api/sentence
        python index.py
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
